const API_KEY ="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"
const HUG_API_KEY ="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"
const OPENAI_API_KEY="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"
export {API_KEY,OPENAI_API_KEY}